Activity.create(:id => 1, :name => "Empty dishwasher", :category => "chore", :points => 5)
Activity.create(:id => 2, :name => "Sports (1 hour)", :category => "physical", :points => 8)
Activity.create(:id => 3, :name => "Reading (English) (1 hour)", :category => "enrichment", :points => 4)
Activity.create(:id => 4, :name => "Paper recyclng", :category => "chores", :points => 2)
Activity.create(:id => 5, :name => "Take out trash", :category => "chore", :points => 4)
Activity.create(:id => 6, :name => "Bottle recycling", :category => "chores", :points => 3)
Activity.create(:id => 7, :name => "Play a sport (1 hour)", :category => "physical", :points => 5)
Activity.create(:id => 9, :name => "Exercise (first 5 min)", :category => "physical", :points => 2)
Activity.create(:id => 10, :name => "Wet recycling", :category => "chore", :points => 4)
Activity.create(:id => 11, :name => "Load dishwasher", :category => "chore", :points => 6)
