Deed.create(:id => 1, :person_id => 1, :activity_id => 2)
Deed.create(:id => 2, :person_id => 1, :activity_id => 3)
Deed.create(:id => 4, :person_id => 11, :activity_id => 1)
Deed.create(:id => 5, :person_id => 5, :activity_id => 9)
Deed.create(:id => 6, :person_id => 11, :activity_id => 3)
Deed.create(:id => 7, :person_id => 11, :activity_id => 6)
Deed.create(:id => 8, :person_id => 13, :activity_id => 10)
Deed.create(:id => 9, :person_id => 4, :activity_id => 10)
Deed.create(:id => 10, :person_id => 4, :activity_id => 11)
Deed.create(:id => 11, :person_id => 11, :activity_id => 4)
Deed.create(:id => 12, :person_id => 11, :activity_id => 6, :points => 5)
Deed.create(:id => 13, :person_id => 4, :activity_id => 10, :points => 6)
