Person.create(:id => 1, :name => "Joe Blow", :password_digest => "$2a$10$Ixdlv0OQ4OrXuj1vq0X4HuVb6VysqejEuufqTSR3cizACJmyd9rkG", :remember_token => "loKOxwnvcndvWm-joXSJXA", :admin => false)
Person.create(:id => 3, :name => "Adin", :password_digest => "$2a$10$VQi8t8aeL65g7pMMT5sdFOzN0sn73gjXSfKDVPKej9yonHph/ItvG", :remember_token => "_gkYyvFGVHVqHJGhquFqOw", :admin => false)
Person.create(:id => 4, :name => "Chaim", :password_digest => "$2a$10$dFyzrtzCxbAlfpdkKwS/y.V3Nxg0XcPXisxjLxHmE4z9kG72N9yHO", :remember_token => "m4khES-3nbMIfZXhXI9rnw", :admin => true)
Person.create(:id => 5, :name => "Ariella", :password_digest => "$2a$10$OXLcACaF8/VivMUWKGf/reRp/yKwyWwSrIldx2OlRCWCvA7f4BSFu", :remember_token => "bHFoTLGxxoplHJ4_jgWzKw", :admin => false)
Person.create(:id => 6, :name => "Calanit", :password_digest => "$2a$10$UiphnQYlZ/vlxABFe8MkBu4.wI9ZL4RH0KH57W7bNWaC6wR6tbKLm", :remember_token => "ofGDMcT9qR9_fUfUIX3EFw", :admin => false)
Person.create(:id => 11, :name => "test user 2", :password_digest => "$2a$10$yyuBShQjqXukr605ZtihkOeAGoxlSSxmyfu451MO555QxKQFH/e32", :remember_token => "-evJ5gartFpjMopLsXlUjw", :admin => false)
Person.create(:id => 13, :name => "test admin", :password_digest => "$2a$10$f9vsl57OqxHO70qKhgR50O7QrZBxpgoEkhGFTIOyfXVh8jkLp95Ie", :remember_token => "gzy_oqvuP1oTWKIgmU_o1g", :admin => true)
Person.create(:id => 22, :name => "test user 3", :password_digest => "$2a$10$LwLZBR57OODdbQI5QcKfiug3VIe4d79rdkW6yKfQ6tA7ZtiKRSWb.", :remember_token => "N85uXthpZLr10dYbG2ksmg", :admin => false)
Person.create(:id => 23, :name => "admin", :password_digest => "$2a$10$k3QAM1.Hu.QVakcVvkfKI.iOuntFkM5HHHthUpD9vtEPKUpyZY74C", :remember_token => "0shxkePoSpcDYcUo5W0HUw", :admin => false)
Person.create(:id => 24, :name => "test user 4", :password_digest => "$2a$10$WcqD82Fd6HAEM4/lr4Z09./.Wa5zKQtuxT69ylTjzeQp7BXPQ9Tc.", :remember_token => "S6h8Bl6cjsIwcUw__Mjjig", :admin => false)
Person.create(:id => 25, :name => "hooty", :password_digest => "$2a$10$mzjyaoRYOqvPbM5taSjyOOpKae1/85CR55HOqOBVwZhZoXkgQmhuq", :remember_token => "B9Aeg6QoE5Rh884sA7iQQA", :admin => false)
Person.create(:id => 26, :name => "fruity", :password_digest => "$2a$10$/mEc6YBgDReEJhdSJfrHiuUxC6Bq8qMWwK9/hUopFJk0S8JYg6ioa", :remember_token => "LXePe30tpExhfm0s0xHy2A", :admin => false)
Person.create(:id => 27, :name => "tooty", :password_digest => "$2a$10$YAyH8E9Ns296HCnCmy6QMOoASwAcSNniSU.d6Y9HQ7qSMl53MwN/m", :remember_token => "y25XZlX2uwXN2MlcKxOP8A", :admin => false)
